[package]
name = "rlok"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
rlok_lib = { path = "../rlok_lib"}
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
